FROM nvidia/cuda:11.4.2-devel-ubuntu20.04


WORKDIR /app

COPY . .
#RUN cp /app/vendor/github.com /usr/local/go/src/


ENTRYPOINT ["tail", "-f", "/dev/null"]
#ENTRYPOINT ["/bin/sh", "-c" , "./tfg"]